name: scheduled-linkcheck

on:
  schedule:
    - cron: 0 4 * * 1  # At 04:00 on Monday

jobs:
  sphinx-scheduled-linkcheck:
    name: scheduled-linkcheck
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout to docs repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Perform linkcheck
        shell: bash -l {0}
        run: |
          make linkcheck
